### ISSUE TITLE
Keep the promise

### ISSUE THREAD

**Issue by lucasmartins** [yegor256/xdsd#11]
The PDF on http://www.xdsd.org doesn't detail **what is xdsd**. It just talks about a one-data-point test suggesting it as the ideal implementation.

I suggest keeping the promise:

> In this document we introduce eXtremely Distributed Software Development (XDSD) methodology and explain how it reduces risks and improves quality.

It really doesn't.

Also, there are missing details like this:

> ...we have been developing and experimenting with a methodology called eXtremely Distributed Software Development, that applies the **most important components of OSS success** to commercial teams

What are the **most important components of OSS success**?

> XDSD guarantees commercial projects what they usually tend to lack, i.e. manageability, quality of code, high team morale, and motivated user community.

How does it do it?

I mean no offence, anybody trying to understand the process will ask the same questions.

Keep up the good work,

Cheers,

Lucas.

**Comment by yegor256** [comment]
@lucasmartins thanks for the questions, I'll try to answer them all tomorrow

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
