### ISSUE TITLE
What does the ideal developer look like from the XDSD viewpoint?

### ISSUE THREAD

**Issue by maurezen** [yegor256/xdsd#13]
There are plenty of articles about how XDSD works and about how the developer should organize his work process.

However, there's little about the ideal developer's attitude. What should be the priorities of someone ideally suitable to work under the XDSD paradigm?

[These](http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html#we-pay-only-for-closed-tasks) two [articles](http://www.yegor256.com/2014/04/13/no-obligations-principle.html#how-does-this-affect-me?) seem to suggest that the developer should do everything to accrue as much paid worktime as he can while performing as little actual work as he can, but that doesn't seem like a healthy attitude.

**Comment by yegor256** [comment]
@maurezen good question, I'll try to publish something, in order to answer it. thanks!

**Comment by maurezen** [comment]
@yegor256 when will it be appropriate to ping you about updates on the matter?

**Comment by yegor256** [comment]
@maurezen I don't have enough information for this yet... maybe in a few months.

**Comment by MrTomWhite** [comment]
@yegor256 Did you get more information for this yet? :smile_cat:

**Comment by yegor256** [comment]
@MrTomWhite I think these articles should help you to find an answer to this question:

 * http://www.yegor256.com/2015/01/15/how-to-cut-corners.html
 * http://www.yegor256.com/2015/06/18/good-programmers-bug-free.html
 * http://www.yegor256.com/2015/02/16/it-is-not-a-school.html
 * http://www.yegor256.com/2015/01/26/happy-boss-false-objective.html
 * http://www.yegor256.com/2014/10/26/hacker-vs-programmer-mentality.html

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
