### ISSUE TITLE
the architect has punished if he asked reassign a ticket 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xdsd#19]
Architect's rating decreases when the architect asks the PM to assign a task to someone else. Only the task performer should be punished if he asks about the reassign.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@dmzaytsev yes, it's a valid bug in our management model, thanks for reporting

**Comment by davvd** [comment]
@yegor256 it's yours, please help, budget is 30 mins

**Comment by davvd** [comment]
@dmzaytsev many thanks for the bug report, I added 15 mins to your acc, transaction `66376334`

**Comment by dmzaytsev** [comment]
@yegor256 any progress here ?

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
