### ISSUE TITLE
postponed until other task will be completed

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xdsd#20]
Right now the architect can ask postpone a task only if someone already assigned to the task. It would be nice to have same feature for unassigned tasks.
The PM should notify when linked task will be completed.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@dmzaytsev thank you for reporting this, I added 15 mins to your acc, transaction `66491379`

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
