### ISSUE TITLE
Time allowed for the developer have to be calculated between task assignment and last commit.

### ISSUE THREAD

**Issue by HDouss** [yegor256/xdsd#25]
In XDSD, the time for resolving an issue by a developer is calculated as the time between task assignment and payment time. This calculated time impacts rating bonus, payment bonus, speed delivery calculus and reassignment (and rating decreasing) in case of exceeding certain time.
Sometimes, a the total (sum) time taken by : 
- assignment of a code reviewer (by PM)
- the code review (by reviewer)
- the code merge triggering, or code merge confirmation (by architect)
- the issue closing (by issue reporter)
- time between issue closing and payment
- generally 1h for merging

exceeds 2 or 3 days.
The developer could be penalized (do not have bonuses) by tasks where he is not involved.
The time calculation for bonuses or penalizing should be considered as the time between assignment and his last accepted commit (after code review). That would be fairer.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
