### ISSUE TITLE
Extend QA responsibility to make sure puzzle is removed from code when PR is closed

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#26]
It happens quite often that person solving the puzzle forgets to remove puzzle from the code.

Then only after several days when PM is not closing the task even when asked multiple times to do so it appears that puzzle is just not removed. 

I'd propose to extend QA responsibility to check whether puzzle is removed/changed in the code.

The only corner case here is that there might me several PRs for one puzzle, it happens rarely though. In such case, we may demand description that "puzzle not removed, as this is not final pull request" or something similar.

I don't see possibility to easily automate that as it is hard to tell which commit is last and which one should remove puzzle.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
