### ISSUE TITLE
PR should be verified before it assign to CR

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xdsd#30]
Right now a project manager assigns a code review  to a pull request automatically,  so we have four PR https://github.com/yegor256/takes/issues/541 https://github.com/yegor256/takes/issues/538 https://github.com/yegor256/takes/issues/532 https://github.com/yegor256/takes/issues/528 for the one ticket. Furthermore [this ticket](https://github.com/yegor256/takes/issues/523)  is not confirmed by the architect yet.

I would propose to make some checks before the assignment
- PR description should contains a link to the ticket it is related to.
  PM should post a message with the quote from the policy if the link doesn't exists

> Pull request description explains the solution proposed and contains a link to the original ticket it is related to.
- The link should point to valid ticket that classified as a bug. PM should inform the developer if it's not a bug.
- The developer should be assigned to that ticket. If his github account linked to Teamed.

When the developer posts a message addressed to the project manager, the PR should be checked again

**Comment by yegor256** [comment]
@dmzaytsev good point, thanks

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev many thanks for the bug report, I added 15 mins to your acc, transaction `75337876`

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
