### ISSUE TITLE
Instructions how to update skills should be more clear

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#31]
In 'Teams' tab there's summary of the skills:
![image](https://cloud.githubusercontent.com/assets/5467276/12656750/1a2fd34e-c600-11e5-8b27-dfca03430b74.png)
Instruction is "update us", but it is not specified how update process looks like (bout message? to whom?) and what is the impact of having more skills listed.

It is also not clear for me what types of skills could go there. Is it only about programming languages, or also about major technologies or operating systems?

I'd expect instruction to be more clear and to have at least one sentence explanation what these skills are about.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
