### ISSUE TITLE
In project summary max assigned tasks set to '?' is confusing

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#32]
In 'Teams' tab in project summary at some projects I see `?` at `max` column:
![image](https://cloud.githubusercontent.com/assets/5467276/12656877/e3853bc6-c600-11e5-9f23-46ea85687e5c.png)
It is supposed to represent maximum number of tasks that can be assigned to you in this project. But what `?` is supposed to mean in that case?

I'd expect either all project to define that number, or use infinity character `∞` to indicate unlimited.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
