### ISSUE TITLE
Prepare list of all Teamed projects and their statuses

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#33]
Teamed has many projects across many organizations (`teamed`, `yegor256`, `libreio`, `jcabi`, `sttc`) and it might be confusing especially for new-joiners to see the landscape.

I'd like to have list of all Teamed.io XDSD projects listed on the dashboard in Netbout along with their statuses, e.g. `libreio/libre` or `sttc/stateful` do not look active and I'm not sure whether it makes sense to submit any issues/take tasks in those.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by valery1707** [comment]
I think [aintshy](https://github.com/aintshy) is also belong to Teamed because their projects ([hub](https://github.com/aintshy/hub), [android](https://github.com/aintshy/android), [iOS](https://github.com/aintshy/iOS), [html](https://github.com/aintshy/html)) have badge "Made by: teamed."

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
