### ISSUE TITLE
Paragraph #15 in policy is misleading

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#34]
[§15](http://at.teamed.io/policy.html#15) says that 

> When you complete a task, we'll measure the speed of delivery, which is the time interval between the moment you were informed of the task by the project manager and the moment you were paid for its completion.

But that's not the case in practice. I think that times of delivery are calculated differently for PDD and bugfix tasks and usually it's difference between assignment and closing issue or deploying puzzle.

Let's be more precise in policy.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
