### ISSUE TITLE
Rules of Puzzle-Driven Development

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#35]
There's set of specific rules regarding PDD, but they are not described anywhere. I haven't found anything in the current policy. It is very confusing especially for new joiners.

The following questions should be covered by PDD Policy:
- How the delivery speed is calculated?
- Who is responsible for closing the issue? Should PM be chased to do that?
- What happens if someone forgot to remove puzzle and did it in another PR?
- Who is responsible for doing the deployment? Who should react if deployment has failed?
- Should the task performer be punished for late puzzle delivery if everything was done including merge but deployment has failed due to env issue and no one noticed?

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
