### ISSUE TITLE
Agenda is broken after recent Netbout release

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#36]
Agenda looks as follows after updating Netbout to 2.23:
![image](https://cloud.githubusercontent.com/assets/5467276/12779860/d45a1ba8-ca6a-11e5-957c-d6d02187cd54.png)
Let's bring it to the previous state.

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
