### ISSUE TITLE
PM does not inform assignee about resolved blocker

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#37]
When assignee [informs about task blocker](https://github.com/yegor256/rultor/issues/806#issuecomment-172611905) and then this blocker gets resolved like [here](https://github.com/yegor256/rultor/issues/806#issuecomment-172857690) only issue author is informed by PM, but he doesn't have much interest in it.

It is mainly in interest of task assignee to know that blocker was resolved and work can be started. Please add also task assignee name at the the beginning of message from PM.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
