### ISSUE TITLE
Speed of delivery is not updated recently

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#38]
Despite having many finished tasks recently, the latest task taken to the average is 2 weeks old:
![screenshot from 2016-02-03 21-54-21](https://cloud.githubusercontent.com/assets/5467276/12796785/e81edf7e-cac0-11e5-80dc-ca1c780d8219.png)

I'd expect this table to contain up-to-date information.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
