### ISSUE TITLE
Links to milestones in PM messages are not correct

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#40]
Whenever PM posts information about missed milestone, like e.g. in https://github.com/yegor256/netbout/issues/848#issuecomment-173558992, link is to JSON GitHub API (https://api.github.com/repos/yegor256/netbout/milestones/1).

I'd expect link to UI, like https://github.com/yegor256/netbout/milestones/3.0

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
