### ISSUE TITLE
Paragraphs from QA policy should be numbered and linkeable

### ISSUE THREAD

**Issue by mkordas** [yegor256/xdsd#42]
Right now it is possible only to link to QA policy as a whole: http://at.teamed.io/qa.html

It would be nice to give rules proper numbers and clickable links, so that they could be referred one by one.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@mkordas just click on any paragraph number and you will get a link: http://at.teamed.io/policy.html#3

**Comment by mkordas** [comment]
@yegor256 I meant QA policy on http://at.teamed.io/qa.html, I cannot get links there.

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
