### ISSUE TITLE
§10 and §16 (Granting "More Time") Need Clarification

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/xdsd#45]
Currently asking the PM for more time simply turns off any sort of automatic punishments for delays.
There is absolutely no say on the quantity of additional time in http://at.teamed.io/policy.html#10.
Also I have never seen a request for additional time denied either.
This puts §10 and §16 in a certain contradiction to each other.

This puts the architect and project as a whole in a very unfortunate spot.
The PM has the authority over granting time to developers, the architect has the responsibility for timely delivery. The architect as the person responsible for scheduling tasks should also have a means of controlling the timeframe in which they are handled.

=> Given that tasks are supposed to be small 30 minute increments, wouldn't tightening the rules in the following way be more in the spirit of things?

**I suggest:**
- No extensions on urgent tasks ever. Urgent tasks are an almost meaningless instrument when developers can get extensions on them. On those punishment after 7 days should be automatic.
- Occasional extensions **up to** 10 days without punishment are ok.
  - Why not turn the rule of thumb [here](http://www.yegor256.com/2014/04/20/how-hourly-rate-is-calculated.html#past-due-tasks) into an actual rule? Simply giving developers **one unpunished extension per 20 completed tasks** instead of stating that 5% delayed tasks is a good rule of thumb seems a lot more reasonable.
- No extensions beyond 10 days ever for tasks that still don't have a "reasonable" PR when reaching the 10 day cutoff.
  - The architect should have the decision on what constitutes a "reasonable" PR.

---

I think above suggestion in fact simply affirms §16 and would set clear rules instead of arbitrary ones for what §10 leaves undefined at present.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@original-brownbear good ideas, thanks, I'll implement them soon

**Comment by davvd** [comment]
@original-brownbear many thanks for the bug report, I added 15 mins to your acc, transaction `AP-73G36871FU8985011`

**Comment by longtimeago** [comment]
@original-brownbear in the description by "extensions" you mean "more time" without pointing to another issue, right?
Let's don't forget the case when we have to wait for a bugfix in 3rd party library

**Comment by original-brownbear** [comment]
@longtimeago yea exactly basically all cases not pointing to any proper reason.
I think the import part though is that it should be in the architects hands to grant or not grant an extension ... not an automatic action by the PM.
I mean, it's of direct financial consequence for the ARC if this is abused, hence he needs to have the power to stop it.
Moreover I think this is something even the DEVs win from ... it's a slightly uncomfortable situation to get yourself into when you have a task that you asked for an extension on (probably in all honesty thinking you'll get to it soon) and eventually would rather get rid of. 
Now you currently only have bad choices:
* Just letting it go on ... completely gaming the system, now the architect will reassign you eventually as it is his only way out of being punished for a long running task himself and getting of the hook for free.
* Asking to be reassigned ..., now you hurt yourself the same way had you not asked for the extension in the first place, but also hurt the project by delaying things ...
* Doing the task anyways ( while probably being able to handle 3 other tasks in the same time ) ... hurting yourself and the project 

If you give the architect the control over this, within clearly set rules, then it's just a clear cut situation for everyone involved. DEV and ARC can plan within clear boundaries.
I mean at least to me it seems that the whole issue of "more time" is basically the only slightly "emotional"
topic left ... I barely experience any pointless back and forth in CR, but on this matter we often lose a lot of time asking where and issue is at, getting some empty response of "I'll get to it soon" and whatnot ...

**Comment by longtimeago** [comment]
> I mean, it's of direct financial consequence for the ARC if this is abused, hence he needs to have the power to stop it.

Totally agree on that

**Comment by original-brownbear** [comment]
@amihaiemil @yegor256  I think if you find yourself in a situation of genuine misconduct by CR, you should approach the `ARC` in the respective project.
The `ARC` in a project has the power to merge your work regardless and a financial incentive to speed things along (he will likely still point out the issues CR missed so far). 

@yegor256 correct me if I'm wrong in the below:

In general I understand, the `ARC` is the person to talk to, when it comes to issues with `CR`, as `CR` is simply one of the tools at the disposal of the `ARC`.

**Comment by amihaiemil** [comment]
@original-brownbear The CR came to my mind when writing the comment, but it's not the only thing. Many times I waited for the ARC to approve the merge. One time I waited 3 weeks, pinging every day :)

**Comment by ekondrashev** [comment]
@original-brownbear @yegor256 @amihaiemil 
The most close thing that can be done to enhance the review process, is just to assign a reviewer that has a same/different timezone that a performer, depending on the performer choice.

Let me elaborate. 

There are times when you did a PR in a first day, but the reviewer is assigned from different timezone, so you technically can't provide a solution within 24h.

From the other hand, there are pretty different cases when you've implemented a PR and it would be best if it will be reviewed during night or a beginning of next day to have some overlap with a reviewer, fixing all the comments.

Just my 2 cents.

**Comment by amihaiemil** [comment]
@ekondrashev my problem is not time passing in itself (usually the reviewer is from my timezone as well)... my problem is that time passes and I'm being "punished" for it. If there wouldnt be this "punishment", everything would be ok. Also, im running the risk of losing the task because of it.

**Comment by yegor256** [comment]
@original-brownbear yes, right, code review is one of the instruments of an architect to push the project to the right direction: http://www.yegor256.com/2015/05/13/two-instruments-of-software-architect.html

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
