### ISSUE TITLE
Should probably pay for bur acceptance as well as for reporting

### ISSUE THREAD

**Issue by antonxt** [yegor256/xdsd#9]
A bug reporter is being paid immediately. But later, when developer has worked on the issue, the reporter should invest more time to check whether the bug is properly fixed. However, the person was already paid for reporting and he will not be paid more for checking.

So, why would he do the check properly? That contradicts the [no obligations principle](http://www.xdsd.org/2014/04/13/no-obligations-principle.html), since reporter is implicitly responsible for the bug fix acceptance.

I suggest to split the payment for bug reporting in two parts: first one is paid immediately after a bug is reported (as it is now), the second one - after the bug is closed. Maybe don't even pay for reporting, pay only for closing.

OR, which may be even better, to take this responsibility from a bug reporter and assign it to a manager.

**Comment by davvd** [comment]
The task is done, thanks all, I'm closing it

**Comment by davvd** [comment]
oops, closed by mistake

**Comment by yegor256** [comment]
@original-brownbear I'm closing this task, since it's not relevant to this repo anymore. If you still believe that there is an issue in our [Policy](http://www.zerocracy.com/policy.html), please re-submit it to this repo: [zerocracy/datum](https://github.com/zerocracy/datum/issues)
